use Challenge1;

-- 1. What are the details of all cars purchased in the year 2022?

select c.car_id,make,type,style,cost,extract(year from purchase_date) as 'year' from sales s , cars c where s.car_id=c.car_id and extract(year from purchase_date)=2022;

 -- What is the total number of cars sold by each salesperson?
 select s.salesman_id , name , count(car_id) as 'Cars Sold' from sales s , salespersons sp where sp.salesman_id=s.salesman_id group by salesman_id;
 
 -- What is the total revenue generated by each salesperson?
 SELECT 
    s.salesman_id, name, SUM(cost) AS 'Total revenue'
FROM
    sales s,
    salespersons sp,
    cars c
WHERE
    sp.salesman_id = s.salesman_id
        AND c.car_id = s.car_id
GROUP BY salesman_id;

-- What are the details of the cars sold by each salesperson?
SELECT 
    s.salesman_id, name, c.car_id, make, type, cost, style
FROM
    sales s,
    salespersons sp,
    cars c
WHERE
    sp.salesman_id = s.salesman_id
        AND c.car_id = s.car_id
order BY salesman_id;

--  What is the total revenue generated by each car type?
select type , sum(cost) as 'revenue generated' from cars group by type order by 'revenue generated' desc;

-- What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
SELECT 
sp. salesman_id, sp.name,
    c.car_id,
    make,
    type,
    style,
    cost,
    EXTRACT(YEAR FROM purchase_date) AS 'year'
FROM
    sales s,
    cars c,
    salespersons sp
WHERE
    s.car_id = c.car_id and s.salesman_id=sp.salesman_id and sp.name='Emily Wong' and EXTRACT(YEAR FROM purchase_date)=2021;
    
-- What is the total revenue generated by the sales of hatchback cars?
with styles as (
select style, cost from cars where style='Hatchback')

select style, sum(cost) from styles;

-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
with styles as (
select style, cost  from cars c, sales s  where c.car_id = s.car_id and style='SUV' and extract(year from purchase_date)=2021 )

select style, sum(cost) from styles;

-- What is the name and city of the salesperson who sold the most number of cars in the year 2023?
select name, city 